// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/arigatory/go-musthave-diploma/internal/accrual (interfaces: Store,OrderSource)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=accrual . Store,OrderSource
//

// Package accrual is a generated GoMock package.
package accrual

import (
	context "context"
	reflect "reflect"

	model "github.com/arigatory/go-musthave-diploma/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// PendingOrders mocks base method.
func (m *MockStore) PendingOrders(ctx context.Context, limit int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingOrders", ctx, limit)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingOrders indicates an expected call of PendingOrders.
func (mr *MockStoreMockRecorder) PendingOrders(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingOrders", reflect.TypeOf((*MockStore)(nil).PendingOrders), ctx, limit)
}

// UpdateOrderAccrual mocks base method.
func (m *MockStore) UpdateOrderAccrual(ctx context.Context, number string, status model.OrderStatus, accrual *model.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAccrual", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAccrual indicates an expected call of UpdateOrderAccrual.
func (mr *MockStoreMockRecorder) UpdateOrderAccrual(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAccrual", reflect.TypeOf((*MockStore)(nil).UpdateOrderAccrual), ctx, number, status, accrual)
}

// MockOrderSource is a mock of OrderSource interface.
type MockOrderSource struct {
	ctrl     *gomock.Controller
	recorder *MockOrderSourceMockRecorder
	isgomock struct{}
}

// MockOrderSourceMockRecorder is the mock recorder for MockOrderSource.
type MockOrderSourceMockRecorder struct {
	mock *MockOrderSource
}

// NewMockOrderSource creates a new mock instance.
func NewMockOrderSource(ctrl *gomock.Controller) *MockOrderSource {
	mock := &MockOrderSource{ctrl: ctrl}
	mock.recorder = &MockOrderSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderSource) EXPECT() *MockOrderSourceMockRecorder {
	return m.recorder
}

// Order mocks base method.
func (m *MockOrderSource) Order(ctx context.Context, number string) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order", ctx, number)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Order indicates an expected call of Order.
func (mr *MockOrderSourceMockRecorder) Order(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockOrderSource)(nil).Order), ctx, number)
}
